#version: '3.8'

services:
  spring-app:
    build:
      context: .
    image: anuj0010/ragify:latest
    container_name: ragify
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"

  postgres-db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data



#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.17.0
#    container_name: filebeat
#    user: root
#    volumes:
#      - ./logs:/logs:ro
#      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - spring-app
volumes:
  pgdata:
